### PR TITLE
"Pin json to <2.0.0"

### PR DESCRIPTION
**Pull request by nibalizer**

### CODE REVIEW

**Comment by cwjohnston** [comment]
Hi @nibalizer, thanks for the pull request. Can you please provide some context around why are proposing this change?

**Comment by nibalizer** [comment]
The json gem released today, dropping support for rubies older than 2.0: https://rubygems.org/gems/json/versions/2.0.1

This means we can't install sensu-plugin, unfortunately.

**Comment by nibalizer** [comment]
We ended up moving to ruby2.0 from the trusty packages as a way of moving forward, so I don't need this right now. I can leave this open if you want to do it for the people who don't have that option. Feel free to close it if you want.

Thanks!

**Comment by cwjohnston** [comment]
@nibalizer thanks for the detail and raising this issue. We're now shipping Ruby 2.3.0 in the Sensu omnibus packages. I'll leave this open as I think we'll have to make a decision about how we want to handle this in the next major version of sensu-plugin.

**Comment by SegFaultAX** [comment]
@cwjohnston Many existing sensu plugins support Ruby 1.9.x (and older) and having such a loose dependency on json breaks those plugins. I recommend locking to `json ~> 1.8` or perhaps `json ~> 1.8.3` to preserve backwards compatibility with the huge array of existing plugins.

Example: [sensu-plugins-mysql](https://github.com/sensu-plugins/sensu-plugins-mysql)

**Comment by cwjohnston** [comment]
I think pinning this at < 2.0 is sane 👍

**Pull request merged**
