### PR TITLE
Support SENSU_LOADED_TEMPFILE

### PR DESCRIPTION
**Pull request by portertech**

### CODE REVIEW

**Comment by mattyjones** [comment]
good to me
happy_2016217c

**Comment by tas50** [comment]
This is certainly better than using the ENV which didn't scale.  I do have concerns that users often delete files in /tmp without fully understanding the impact.  That being said this is still an improvement over the previous setup so +1

**Comment by portertech** [comment]
@tas50 perhaps we can improve sensu-build to set a separate TMPDIR for the sensu processes.

**Comment by mattyjones** [comment]
Don't worry about users, if you document this effectively, then it is their problem.

**Comment by mattyjones** [comment]
The TMPDIR specific to sensu would be good, I am a big fan of app specific stuff vs everything living in the system.

**Comment by portertech** [comment]
@mattyjones I always worry about users :)

**Pull request merged**
